version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme-challenges:/usr/share/nginx/html/.well-known/acme-challenge

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
      - ./acme-challenges:/usr/share/nginx/html/.well-known/acme-challenge
    environment:
      - DEFAULT_EMAIL=aarinjasikumar@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: PlanPalDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/frontend-planpal
    container_name: frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=planpal.tech
      - LETSENCRYPT_HOST=planpal.tech

  backend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/backend-planpal
    container_name: backend
    restart: always
    expose:
      - 3000
      - 4001
    environment:
      - VIRTUAL_HOST=api.planpal.tech
      - LETSENCRYPT_HOST=api.planpal.tech
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=PlanPalDB

volumes:
  postgres_data:
